language: node_js
node_js:
 - "12.13.1"

addons:
  chrome: stable

before_script:
  - npm install gh-pages 

cache:
  npm: true
  directories:
    - node_modules

script:
  - npm run deploy


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GIT_TOKEN
  keep-history: true
  on:
    branch: master